### ISSUE TITLE
Update image tag

### ISSUE THREAD

**Issue by hayleyavw** [uccser/verto#241]
To make creating/editing/translating images more user friendly, the following change needs to be implemented:
Currently an image looks like this:
```
{image file-path="http://placehold.it/350x150" caption="Description of the image."}
```
And the suggested change is:
```
{image file-path="http://placehold.it/350x150" caption="true"}

Description of the image.

{image end}
```
Where the caption is the text between the blocks only if `caption` is `true`. There are multiple other parameters that the image tag uses (e.g. alt, alignment, hover-text, etc) but we have decided to pull the caption out as this the most obvious user facing text and therefore want to make it easy for editors to make changes.

This is only the suggested solution and is up for discussion (e.g. do we need to specify `caption="true"`? what happens when there is no caption, do we still use `{image end}` or make it an inline processor?) cc @JackMorganNZ @jordangriffiths01

**Comment by jordangriffiths01** [comment]
My preference would be a block processor that allows either...

```
{image file-path="http://placehold.it/350x150" caption="true"}

Description of the image.

{image end}
```
...for images with captions or...
```
{image file-path="http://placehold.it/350x150"}
```

...for images without captions.

Definitely not an inline processor - these are causing headaches for translations because they aren't treated as a string on their own. There is an inline-image processor which we'll need to deal with at some point, but we can cross that bridge when we get to it!
